# 
# Copyright 2016-2022 Martin Goellnitz
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Environment variables needed:
# OSS_INDEX_USER
# OSS_INDEX_TOKEN
# COVERALLS_REPO_TOKEN
# CODECOV_TOKEN
#
image: amazoncorretto:11

stages:
  - dinistiq

variables:
    GRADLE_USER_HOME: /tmp/.gradle

build:
  stage: dinistiq
  script:
  - ./gradlew -PossindexUser="$OSS_INDEX_USER" -PossindexToken="$OSS_INDEX_TOKEN" build jacocoTestReport audit generatePomFileForMavenJavaPublication
  - ./gradlew -PossindexUser="$OSS_INDEX_USER" -PossindexToken="$OSS_INDEX_TOKEN" coverallsJacoco
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
  - ./codecov
  artifacts:
    paths:
    - build/libs/*
    expire_in: 5 days
    name: ${CI_BUILD_STAGE}

release:
  stage: dinistiq
  only:
    - tags
  script: ./gradlew build generatePomFileForMavenJavaPublication
  artifacts:
    paths:
    - build/libs/*
    expire_in: 1 days
    name: ${CI_BUILD_STAGE}

cache:
  paths:
  - /tmp/.gradle/caches/
  - /tmp/.gradle/wrapper/
