sudo: false

language: java

jdk:
  - oraclejdk8

after_success:
  - gradle jacocoTestReport coveralls build generatePomFileForMavenJavaPublication artifactoryPublish
  - bash <(curl -s https://codecov.io/bash)
  